### ISSUE TITLE
Downloaded songs appear in white text (unreadable)

### ISSUE THREAD

**Issue by BrianValente** [BrianValente/SpotifyDesktop-LightPurple#1]
In offline mode, downloaded songs appear in white text while unavailable songs appear in black.

**Comment by iykex** [comment]
How to install these theme? i am on ubuntu

**Comment by BrianValente** [comment]
@iykequame Download the latest release and extract all the .spa files in /usr/share/spotify/Apps

**Comment by iykex** [comment]
@BrianValente it's fine now, working , Thanks. and its awesome, cool Theme.

<a href='https://postimages.org/' target='_blank'><img src='https://s33.postimg.org/ni3lz61hb/Deepin_Screenshot_google-chrome_20171119080720.png' border='0' alt='Deepin_Screenshot_google-chrome_20171119080720'/></a>

**Comment by sercansolmaz** [comment]
How to install these theme? i am on Mac Os X.. I do not know much about github, unfortunately

**Comment by BrianValente** [comment]
Fixed.
